*chapter_2_1|第2章
[cm]
;;♪：停止
[stopbgm]
;;♪：残酷な結末
;;□：自室ベランダ(夜)
;;∫：ビジュアルノベル(ノーマル)

[fadeoutmessage]
[transcombo storage="べらんちょ.jpg" time=500 method=crossfade]
[fadeinmessage]
[ct]

[playbgm storage=sekirei.ogg loop=true]
夏も終わりだというのに、暑さは相変わらず緩みを見せない。[lrcm]
亜紗奈に言われたとおりに準備を済ませ、オレはベランダに出ていた。[lrcm]
空では既にたくさんの星たちが、鬱陶しいほど煌めいている。[lrcm]
亜紗奈も向こうの部屋で待っていたらしく、窓際で手招きをしていた。[lrcm]
　【和真】[r]
「ちょっと怖いな…………」[lrcm]
二階建て、柵を隔てただけの両室。[lrcm]
下を覗くと、それは想像よりももっと高い場所にあった。[lrcm]
子どもの頃は、よくここからお互いの部屋を行き来していたが、今では腰が抜けそうになるほど怖い。[lrcm]
（でも、いくしかない…………）[lrcm]
オレがここから亜紗奈の部屋に入り込まなければ、計画を[ruby text="かん"]完[ruby text="すい"]遂することはできない。[lrcm]
意を決して、オレは柵に脚をかけた。[lrcm]
再び下を見ると、脚がすくみそうになる。[lrcm]
（亜紗奈……………………）[lrcm]
正面を向けば、亜紗奈が両手を組んで祈るように見守ってくれていた。[lrcm]
……………………。[lrcm]
…………。[lrcm]
しばらくして――――[lrcm]
　【和真】[r]
「ふぅ……………………」[lrcm]
ベランダを無事に渡り、亜紗奈の部屋へと辿りついた。[lrcm]
;;[stopbgm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
*chapter_2_2|第2章
;;[playbgm storage=奈落への旋律.ogg loop=true]
　【亜紗奈】[r]
「お疲れさま！　冷や冷やしながら見てたよ」[lrcm]
　【和真】[r]
「いやー、久しぶりだったからさ」[lrcm]
亜紗奈の笑顔を見て、少しだけ安心した。[lrcm]
オレの額に流れる汗の理由は、夏の暑さだけではないだろう。[lrcm]
[image storage="私服_真顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「和むのはまだ早いよ。これからだからね」[lrcm]
　【和真】[r]
「あぁ、わかってるよ」[lrcm]
;;[stopbgm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
*chapter_2_3|第2章
;;[playbgm storage=穢れ.ogg loop=true]
　【亜紗奈】[r]
「それじゃあ、早速行こっか」[lrcm]
亜紗奈の計画を実行し、二人のアリバイを作る。[lrcm]
　【亜紗奈】[r]
「おじいちゃんは今リビングにいると思うから、リビングに向かうよ？」[lrcm]
[image storage="私服_真顔.png" layer=0 page=fore visible=true pos=right_center]
オレは初めから、亜紗奈の部屋にいたことにするというものだ。[lrcm]
当然、亜紗奈の祖父に嘘をつくということになる。[lrcm]
昔からよくしてもらっている人を裏切るような形になってしまったことに、心苦しさを感じた。[lrcm]
亜紗奈の部屋からリビングへと向かう。[lrcm]
久しぶりにきた亜紗奈の家は、以前とほとんど変わっていない。[lrcm]
　【亜紗奈】[r]
「いい？　さっき私が言った通りにするんだよ？」[lrcm]
　【和真】[r]
「わかってる」[lrcm]
緊張から、生返事になってしまう。[lrcm]
;;[stopbgm]
[image storage="私服_悲しみ.png" layer=0 page=fore visible=true pos=right_center]
*chapter_2_4|第2章
;;[playbgm storage=奈落への旋律.ogg loop=true]
　【亜紗奈】[r]
「本当に大丈夫……？」[lrcm]
　【和真】[r]
「ごめん、ちょっと緊張してて……」[lrcm]
何せ、これを失敗すると――――[lrcm]
演技力には自信がないので、不安な気持ちで一杯になる。[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「大丈夫、私がフォローするから！」[lrcm]
その言葉のおかげで、少しだけ不安感を取り除くことができた。[lrcm]
[stopbgm]
*chapter_2_5|第2章
[image storage="私服_微笑.png" layer=0 page=fore visible=false pos=right_center]
……………………。[lrcm]
…………。[lrcm]
[fadeoutmessage]
[transcombo storage="リビング前_夜.jpg" time=2000 method=crossfade]
[fadeinmessage]
リビングの前に到着し、呼吸を整える。[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
*chapter_2_6|第2章
　【亜紗奈】[r]
「大丈夫、落ち着いてやれば必ずできるから」[lrcm]
小声でそう言って微笑む亜紗奈に、オレは頷きを返す。[lrcm]
そして、静かに、ゆっくりと扉を開けた――――[lrcm]
[fadeoutmessage]
[transcombo storage="living4.jpg" time=2000 method=crossfade]
[fadeinmessage]
[image storage="私服_微笑.png" layer=0 page=fore visible=false pos=right_center]
　【和真】[r]
「おじさん、お久しぶりです！」[lrcm]
[playbgm storage=rara.ogg loop=true]
緊張から、少しだけ語調が強くなってしまったけれど、なんとか最初の一言を絞り出すことができた。[lrcm]
*chapter_2_7|第2章
　【亜紗奈の祖父】[r]
「おぉ、和真くんか！　久しぶりだなぁ」[lrcm]
久しく見た亜紗奈の祖父は、なんだか少しだけやつれたような気がした。[lrcm]
　【和真】[r]
「さっきは、ろくに挨拶もせずにお邪魔してすみません」[lrcm]
　【亜紗奈の祖父】[r]
「ん？　今来たんじゃぁないんか？」[lrcm]
[ruby text="うち"]団[ruby text="わ"]扇をパタパタと扇ぎながら、亜紗奈の祖父は不思議そうな顔をしている。[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
*chapter_2_8|第2章
　【亜紗奈】[r]
「おじいちゃん、気がつかなかったの？　お昼過ぎあたりに、私が和真を呼んだのよ？」[lrcm]
　【亜紗奈】[r]
「それで、さっきまで一緒に勉強してたの」[lrcm]
　【和真】[r]
「しっかりと挨拶できればよかったんですが…………」[lrcm]
　【亜紗奈】[r]
「おじいちゃん、そのときトイレにいたものね」[lrcm]
　【亜紗奈の祖父】[r]
「おぉ、そうかそうか。それは悪いことをしたなぁ。知っていれば、茶菓子くらい出したものを」[lrcm]
　【和真】[r]
「いえいえ、お構いなく」[lrcm]
　【亜紗奈の祖父】[r]
「和真くんこそ、そんなにかしこまらんでもいいんだよ？　昔みたいに、おじいちゃんと呼んでもらっても」[lrcm]
昔と変わらない優しげな口調を、懐かしく思った。[lrcm]
オレは今、この人を騙しているのだ――――[lrcm]
そう思うと、心が痛くなった。[lrcm]
　【和真】[r]
「それじゃあオレ、そろそろ帰ります」[lrcm]
この言葉は、この計画になくてはならない存在。[lrcm]
オレは今日、この家に泊まらなくてはならない。[lrcm]
*chapter_2_9|第2章
[image storage="私服_真顔_口.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「えぇ、もう帰っちゃうの？　夏休みなんだし、泊まっていけばいいじゃない」[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「ねぇ、おじいちゃん」[lrcm]
亜紗奈はそう言って、リビングのソファーで優しげに微笑んでいるおじさんに、同意を求める。[lrcm]
彼女の計画では、快く同意が得られることになっていた。[lrcm]
　【亜紗奈の祖父】[r]
「親御さんがそれでいいなら、ワシは構わんよ。ゆっくりしていくといい」[lrcm]
　【亜紗奈】[r]
「和真のお父さんとお母さん、今日は仕事で帰ってこられないみたいで」[lrcm]
　【亜紗奈の祖父】[r]
「おぉ、そうか。それなら、遠慮無く泊まっていっていいんだよ？」[lrcm]
　【亜紗奈】[r]
「ほら、おじいちゃんもそう言ってるんだし、泊まっていったら？　そうすれば、勉強の続きもできるし」[lrcm]
亜紗奈が目で合図をする。[lrcm]
*chapter_2_10|第2章
　【和真】[r]
「それじゃあ、お言葉に甘えて」[lrcm]

――――これでいい。[lrcm]
あとは亜紗奈の言う通りにすれば。[lrcm]
――――オレは助かる。[lrcm]
自分の罪を背負うことなく。[lrcm]
罪悪感など、感じなくてもいい。[lrcm]
[image storage="私服_笑顔_開眼.png" layer=0 page=fore visible=true pos=right_center]
*chapter_2_11|第2章
　【亜紗奈】[r]
「着替えだけ持ってきたらいいんじゃない？　お風呂はうちで入っていけばいいし」[lrcm]
　【亜紗奈の祖父】[r]
「おぉ、そうだそうだ。今日も暑かったから、汗をかいただろう。遠慮する必要はないんだよ？」[lrcm]
　【和真】[r]
「あ、はい。お言葉に甘えて」[lrcm]
　【亜紗奈】[r]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
「それじゃあ、いったん和真の家に行ってくるね」[lrcm]
　【亜紗奈の祖父】[r]
「気をつけていってくるんだよ。とはいっても、隣だから心配もないなぁ」[lrcm]
楽しげに笑うおじさんに合わせるように、オレと亜紗奈は笑い声を作る。[lrcm]
 【亜紗奈】[r]
「行ってきまーす」[lrcm]
*chapter_2_12|第2章
[image storage="私服_笑顔.png" layer=0 page=fore visible=false pos=right_center]

　【和真】[r]
「お邪魔しましたー」[lrcm]
そう言って、亜紗奈の家を出る。[lrcm]
……………………。[lrcm]
;;[stopbgm]
*chapter_2_13|第2章
;;[playbgm storage=穢れ.ogg loop=true]
;;□：自宅玄関先(夜)
[fadeoutmessage]
[transcombo storage="主人公家.jpg" time=2000 method=crossfade]
[fadeinmessage]
*chapter_2_14|第2章
[playse storage=door_a_close.mp3]
――――ガチャン。[lrcm]
……………………。
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「和真、お疲れさま」[lrcm]
　【和真】[r]
「なんとかなったかな…………？」[lrcm]
演技力には自信がなかったから、うまく誤魔化すことができたか一抹の不安がある。[lrcm]
　【亜紗奈】[r]
「大丈夫、和真はよくできたよ」[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=false pos=right_center]
　【亜紗奈】[r]
「ご褒美ね」[lrcm]
そう言って亜紗奈は、オレを抱擁した。[lrcm]
　【和真】[r]
「あ、亜紗奈……？」[lrcm]
再び包まれる、温かで柔らかな感触。[lrcm]
こうしていると、心が落ち着いてくる。[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「はい、おしまいっ」[lrcm]
　【和真】[r]
「あっ…………」[lrcm]
なんだか少しだけ、名残惜しい感じがした。[lrcm]
[image storage="私服_悲しみ_照れ.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「ごめんね。私へのご褒美になっちゃった……」[lrcm]
亜紗奈は顔を赤らめてそう言う。[lrcm]
今オレの心の支えになっているのは、間違いなく亜紗奈だ。[lrcm]
愛おしさにも似た感覚が、オレの心を支配する。[lrcm]
　【亜紗奈】[r]
「ほ、ほら……着替え、持ってこないと」[lrcm]
　【和真】[r]
「あ、そうだった…………」[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
;;[stopbgm]
　【亜紗奈】[r]
「私も、和真の部屋に行っていい？」[lrcm]
　【和真】[r]
「あぁ、別にいいけど。何か用事でもあるのか？」[lrcm]
　【亜紗奈】[r]
「ちょっとね。回収しなくちゃいけないものが……」[lrcm]
;;[playbgm storage=穢れ.ogg loop=true]
　【和真】[r]
「回収……？」[lrcm]
　【亜紗奈】[r]
「ほらほら、いいから。早く戻らないと、何かしてるんじゃないかって疑われちゃうかもよ？」[lrcm]
　【和真】[r]
「わ、わかったよ…………」[lrcm]
[fadeoutmessage]
[transcombo storage="自宅廊下1階_夜.jpg" time=1000 method=crossfade]
[fadeinmessage]
亜紗奈と一緒に、自室に戻る。[lrcm]
[fadeoutmessage]
[transcombo storage="部屋カーテン_夜.jpg" time=1000 method=crossfade]
[fadeinmessage]
（何を回収するんだろう…………）[lrcm]
そう思ったけれど、あまり気にしないことにした。[lrcm]
何か、亜紗奈の考えがあるのだろう。[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「和真は、服を選んでてね」[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=false pos=right_center]
そう言って亜紗奈は、部屋の隅でそそくさと何かを始める。[lrcm]
（さてと……どうしようかな…………）[lrcm]
この期に及んで服選びなんておかしい話だけれど、女の子の家に泊まるのだから、少しは気にしなくてはいけないと思った。[lrcm]
[stopbgm]
――――そんなことを考えていたとき、ふと一つの疑問が頭に浮かんだ。[lrcm]
（亜紗奈は、オレが怖くないんだろうか…………）[lrcm]
*chapter_2_15|第2章
[playbgm storage=穢れ.ogg loop=true]
殺人を犯した人間と一緒にいたら、普通は怖くなりそうなものだけれど。[lrcm]
いくら亜紗奈が凛を恨んでいたとしても、常人の考えであれば、犯罪者と一緒にいるなんてどう考えても恐ろしい。[lrcm]
しかし、亜紗奈は怖がる表情を一切見せていない。[lrcm]
それどころか、無残な殺人現場を見て笑顔すら見せたのだ。[lrcm]
亜紗奈はオレを好きだと言ってくれたけれど、いくら好きな人とはいえ、怖くないわけがない。[lrcm]
彼女は一体、今回のことをどう考えているのだろう。[lrcm]
オレは――――[r]
;選択肢
[link target=*dummy1_1]亜紗奈に訊いてみる。[endlink][r]
[link target=*dummy1_2]今は、やめておく。[endlink][r]
[s]

*dummy1_2
[cm]
*chapter_2_15.3|第2章
そんなこと、今訊いても意味がないだろう。[lrcm]
亜紗奈は、オレの味方なのだから。[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「和真、着替えは準備できた？」[lrcm]
あれこれと思考を巡らせていると、先ほどまで背を向けていた亜紗奈が、こちらの様子を覗っていた。[lrcm]
 [jump target=*chapter_2_16.5]
[s]
*dummy1_1
[cm]
*chapter_2_15.5|第2章
亜紗奈はまだ、こちらに背を向けて何かをしている。[lrcm]
　【和真】[r]
「亜紗奈…………」[lrcm]
[image storage="私服_真顔_口.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「どうしたの、和真」[lrcm]
柔らかな声で返事をする亜紗奈を見て、疑問は更に深まった。[lrcm]
　【和真】[r]
「亜紗奈は……その……オレが怖くないのか…………？」[lrcm]
――――こんなことを訊くのは今さらだけれど。[lrcm]
　【亜紗奈】[r]
「なんで？」[lrcm]
　【和真】[r]
「普通、殺人犯なんかと一緒にいたら、怖くなるもんじゃないのか？」[lrcm]
そんな表情すら見せない亜紗奈。[lrcm]
それどころか、オレを守ってくれるとすら言っている。[lrcm]
[image storage="私服_照れ微笑.png" layer=0 page=fore visible=true pos=right_center]

[stopbgm]

[playbgm storage=sekirei.ogg loop=true]

　【亜紗奈】[r]
「大好きな人と一緒にいて、怖いと感じる人なんていないよ…………」[lrcm]
　【亜紗奈】[r]
「それに――――」[lrcm]
亜紗奈は続けて――――[lrcm]
　【亜紗奈】[r]「私は、どんな和真でも受け入れる。たとえ和真が悪いことをしたとしても…………」[lrcm]
　【和真】[r]
「亜紗奈…………」[lrcm]
　【亜紗奈】[r]
「何度も言ったでしょ？　私は、和真とずっと一緒にいたいの」[lrcm]
　【亜紗奈】[r]
「この気持ちだけは、ずーっと変わらない。どんなことがあってもね」[lrcm]
　【和真】[r]
「そ、そんなこと言ったって…………」[lrcm]
オレは、亜紗奈を受け入れるなんて一言も言っていない。[lrcm]
それどころか、受け入れろとも言われていない。[lrcm]
亜紗奈は、どう思っているのだろうか。[lrcm]
　【和真】[r]
「亜紗奈は……オレと付き合いたいとか思わないのか…………？」[lrcm]
自意識過剰な質問だったのかもしれない。[lrcm]
だけれども、好きだと言われている以上、そう訊いたとしてもおかしくはないはずだ。[lrcm]
　【亜紗奈】[r]
「人と人がずっと一緒にいることに、恋人かどうかなんて関係ないよ」[lrcm]
　【和真】[r]
「え……？」[lrcm]
　【亜紗奈】[r]
「恋人かどうかなんて、周りの指標でしかないの。二人が愛し合っていれば、そんなの関係ないことだから」[lrcm]
[image storage="私服_真顔.png" layer=0 page=fore visible=true pos=right_center]
*chapter_2_16|第2章
　【亜紗奈】[r]
「でも、この女はね。和真と私が一緒にいる時間を奪った」[lrcm]
部屋の中央に置かれている黒い塊を見下ろして、亜紗奈は続ける――――[lrcm]
　【亜紗奈】[r]
「私、自殺しようかと思ったの。和真と一緒にいられないのなら、死んだほうがマシだって」[lrcm]
　【亜紗奈】[r]
「でも、私が死んだとしても、和真と一緒にいられないもの。そんなの、地獄にいるのと同じこと」[lrcm]
[image storage="私服_微笑.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「だからこの女が死んで、もう一度私と和真が一緒にいられる時間ができて、私は今とっても嬉しいの」[lrcm]
　【和真】[r]
「あ、亜紗奈…………」[lrcm]
　【亜紗奈】[r]
「和真は気に病む必要なんてないよ。これは全部、私が望んでいた結果だから」[lrcm]
　【亜紗奈】[r]
「和真は、今回のことは全て私がやったと思うようにすればいい。うん、それがいいよ」[lrcm]
　【和真】[r]
「そ、そんなこと…………」[lrcm]
亜紗奈自らが、責任を押しつけていいと言っている。[lrcm]
身勝手にも、そんな提案を受け入れようとしている自分に嫌気が差した。[lrcm]
　【亜紗奈】[r]
「それよりも、着替えは準備できたの？」[lrcm]

*chapter_2_16.5|第2章

　【和真】[r]
「あ、まだだった……！」[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「私の用事は終わったよ。和真も、早く早くっ。今日はお泊まり会だよ！」[lrcm]
楽しげにはしゃいでいる亜紗奈を見て、オレは思わず笑ってしまった。[lrcm]
[stopbgm]
[playbgm storage=日常パート.ogg loop=true]
　【亜紗奈】[r]
「枕投げとかしよーよっ。ていはんぱつまーくらっ」[lrcm]
　【和真】[r]
「亜紗奈ははしゃぎすぎだって」[lrcm]
　【亜紗奈】[r]
「だってさ、和真がうちに泊まりにくるなんて、久しぶりなんだもの。テンションがあがるに決まってるじゃないっ」[lrcm]
[image storage="私服_どや.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「一緒のお布団で寝るー？」[lrcm]
　【和真】[r]
「ぶふっ。お、お前！」[lrcm]
思わず咳き込んでしまう。[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「冗談だよ？　1割くらいはっ」[lrcm]
　【和真】[r]
「ほぼ本気じゃないかよ」[lrcm]
[image storage="私服_どや.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「あ、でも。そんなことしたら、和真が野獣になっちゃうかなー？」[lrcm]
　【和真】[r]
「オレは奥手だから、何もしないっつーの！」[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「自分で奥手とか言っちゃうんだ。和真って面白いねーっ」[lrcm]
　【和真】[r]
「ば、バカにするなよ……！」[lrcm]
[stopbgm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=false pos=right_center]
;;▲：立ち消し
*chapter_2_17|第2章
……………………。[lrcm]
[playbgm storage=rara.ogg loop=true]
人を殺めて舌の根も乾かぬうちに、楽しげな会話を繰り広げている。[lrcm]
そんな環境に慣れてきた自分がいた。[lrcm]
亜紗奈が――――気を遣ってくれてるのだろう。[lrcm]
彼女のおかげで、オレはいつも通りの自分に戻りつつあった。[lrcm]
自分の罪も忘れて――――[lrcm]
凛を殺めたことも忘れて――――[lrcm]
それは、許されざる大罪。[lrcm]
殺人を犯して、その罪をなかったことにする。[lrcm]
後ろめたさは感じるものの、そうできる環境に甘えてしまう。[lrcm]
オレはつくづく、弱い人間だ。[lrcm]
――――正義感なんてない。[lrcm]
倫理観なんて、オレの知るところではない。[lrcm]
オレは、この罪を受け入れる必要はない。[lrcm]
この殺人の罪は、オレのものではないのだから――――[lrcm]
そんな自分勝手な解釈をして、自分を落ち着けた。[lrcm]
……………………。[lrcm]
…………。[lrcm]
……。[lrcm]

;;♪：停止
[stopbgm]
;;□：ブラックアウト/フェード3秒
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=2000 method=crossfade]

;;★：2秒が適切なら2秒に変更してもよい

;;□：篠倉家玄関先(夜)

[transcombo storage="亜紗奈家_夜.jpg" time=1000 method=crossfade]
[fadeinmessage]

*chapter_2_18|第2章
;;♪：平穏な日常

[playbgm storage=日常パート.ogg loop=true]
　【亜紗奈】[r]
「ただいまー」[lrcm]
　【和真】[r]
「お邪魔します」[lrcm]
[fadeoutmessage]
[transcombo storage="リビング前_夜.jpg" time=1000 method=crossfade]
[fadeinmessage]
着替えの準備を終えて、亜紗奈の家に戻る。[lrcm]
　【亜紗奈の祖父】[r]
「おぉおぉ。おかえり」[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「お風呂の準備はできた？」[lrcm]
　【亜紗奈の祖父】[r]
「言われたとおりやっておいたから、安心しなさい。和真くんが寝る部屋も、用意しておいたから」[lrcm]
　【亜紗奈】[r]
「ありがと！」[lrcm]
おじさんは頷くと、リビングのほうへ戻っていった。[lrcm]
　【亜紗奈】[r]
「お風呂もう入れるよ？　入ってきて」[lrcm]
　【和真】[r]
「オレはあとでいい」[lrcm]
[image storage="私服_どや.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「そうやって、私が入ったあとのお湯を、チューチューするんですね？」[lrcm]
　【和真】[r]
「がっ！　バカ、違うっての！」[lrcm]
――――思わず叫んでしまう。[lrcm]
　【亜紗奈】[r]
「なんでそんなにおどおどしてるのかなー？」[lrcm]
（こいつ、面白がってるな…………）[lrcm]
仕返しをしてやらなくては、男が廃る。[lrcm]
　【和真】[r]
「亜紗奈は、オレが入ったあとのお湯をチューチューするんだろ？」[lrcm]
嫌味のような感じで言ってやったのだけれど――――[lrcm]
[image storage="私服_悲しみ_照れ.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「え………………？」[lrcm]
（そんな反応されても…………）[lrcm]
　【和真】[r]
「お、おい……」[lrcm]
上目遣いで――――[lrcm]
　【亜紗奈】[r]
「だ、ダメ…………？」[lrcm]
　【和真】[r]
「は…………！？」[lrcm]
（だ、ダメって何がだ…………！？）[lrcm]
　【和真】[r]
「おい！　なな、何がだよ……！」[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「なーんてね。和真はかわいいなぁ」[lrcm]
完全に、亜紗奈のペースに乗せられてしまった。[lrcm]
　【和真】[r]
「あーもう。わかったよ、オレが先に入ればいいんだろ？」[lrcm]
[image storage="私服_照れ.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「そんな、怒っちゃダメだよっ」[lrcm]
　【和真】[r]
「いや、別に怒ってはいないけど」[lrcm]
　【亜紗奈】[r]
「一緒に入りたい…………？」[lrcm]
　【和真】[r]
「な、なんでそうなるんだよ……！」[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「ごめんごめんっ。これは私の願望でしたー」[lrcm]
　【和真】[r]
「えっ…………？」[lrcm]
[image storage="私服_どや.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「やだなぁ本気にしちゃって。冗談だよ、冗談」[lrcm]
　【和真】[r]
「お前の冗談って、結構笑えないときあるよな……」[lrcm]
[image storage="私服_笑顔.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「はいはい、ごめんね」[lrcm]
　【亜紗奈】[r]
「それじゃあ、一緒にお風呂入ろっか」[lrcm]
　【和真】[r]
「だ、だからーー！」[lrcm]
　【亜紗奈】[r]
「いやー！　和真が襲ってくるぅーーー！」[lrcm]
そんなことを棒読みで言う亜紗奈に、なんとか一矢報いようとしても――――[lrcm]
　【和真】[r]
「そんなこと言ってると、本当に襲うぞ！」[lrcm]
[image storage="私服_発情.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「うん、待ってるね…………」[lrcm]
　【和真】[r]
「っておぉい！」[lrcm]
――――こんな風に、反撃を食らうのだった。[lrcm]
[image storage="私服_発情.png" layer=0 page=fore visible=false pos=right_center]
[stopbgm]
;;□：ブラックアウト／フェード3秒
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=3000 method=crossfade]
[fadeinmessage]

;;★：4秒にする可能性あり

;;□：亜紗奈の部屋(夜)
[fadeoutmessage]
[transcombo storage="亜紗奈部屋_夜.jpg" time=1000 method=crossfade]
[fadeinmessage]
*chapter_2_19|第2章
[playbgm storage=rara.ogg loop=true]
風呂から上がったあと、そのまま亜紗奈の部屋に通された。[lrcm]
……………………。[lrcm]
…………。[lrcm]
――――なんとなく落ち着かない。[lrcm]
本人不在で女の子の部屋に入るというのは、なかなか緊張するものだ。[lrcm]
（凛と付き合っていた頃は、部屋に入るなんてことなかったな…………）[lrcm]
凛と交際していた今日までの記憶。[lrcm]
それらはもう、鮮やかな青春の色とはほど遠いものに成り代わっていた。[lrcm]
今日がなければ、二人はまだ恋人同士だったのだろうか。[lrcm]
――――いや、きっと遅かれ早かれ、終わっていたのかもしれない。[lrcm]
殺人という最悪な行為で終わらせてしまった。[lrcm]
――――オレは、最低な人間だ。[lrcm]
そんなこと、既に知っている。[lrcm]
いや、正確には今日知った。[lrcm]
おぞましくも汚らわしい、この手。[lrcm]
この手で、凛を突き飛ばした。[lrcm]
突き飛ばしたりさえしなければ。[lrcm]
突き飛ばしたこの手さえなければ。[lrcm]
一人になると、負の感情だけが頭を支配する。[lrcm]
人を殺した人間が今こうして、ヘラヘラと笑いながら、何の罪も背負わずに生きているのだ。[lrcm]
祟られてもおかしくないだろう。[lrcm]
――――いや、むしろ。[lrcm]
祟られて楽になりたい。[lrcm]
誰かオレを殺してくれとさえ、懇願したくなるほどに。[lrcm]
オレの心は荒んでいく。[lrcm]
凛を殺した時点で、オレはもう元には戻れないのだ。[lrcm]
あの時、あの瞬間から。[lrcm]
[stopbgm]
*chapter_2_20|第2章
;;★：特殊効果(回想：開始)
;;□：自室(昼)
[image storage="部屋_回想.jpg" layer=base page=fore visible=true]

時計は16時をまわったころだった。[lrcm]
[playse storage=doorbell.mp3]
――――ピンポーン。[lrcm]
玄関のチャイムが鳴る。[lrcm]
　【和真】[r]
「ん？　誰だろ？」[lrcm]
両親は仕事で出かけていたため、留守。[lrcm]
オレが出るのが、当たり前だった。[lrcm]
　【和真】[r]
「せっかく、いつもより勉強がはかどってたのに…………」[lrcm]

;;□：廊下(夕)／フェード2秒
[fadeoutmessage]
[transcombo storage="廊下回想.jpg" time=1000 method=crossfade]
[fadeinmessage]


;;□：玄関(夕)
[fadeoutmessage]
[transcombo storage="玄関回想.jpg" time=1000 method=crossfade]
[fadeinmessage]
*chapter_2_21|第2章
文句を言いながらも、しぶしぶ玄関に向かう。[lrcm]
玄関先には、ドアの曇りガラス越しに見知った姿があった。[lrcm]
　【和真】[r]
「おぉ！　凛じゃないか」[lrcm]
慌ててドアを開ける。[lrcm]
　【[ruby text="りん"]凛】[r]「や、やぁ。か、和くん」[lrcm]

;;★：修正する可能性あり

[playbgm storage=rara.ogg loop=true]
目の前にいるのは、オレの恋人の[ruby text="な"]那[ruby text="す"]須[ruby text="かわ"]川[ruby text="りん"]凛だった。[lrcm]
付き合い始めてまだ数ヶ月。[lrcm]
凛のほうから告白し、付き合うことになったのは記憶に浅い。[lrcm]
　【和真】[r]
「なんの連絡もなしに訪ねてくるなんて、珍しいな」[lrcm]
　【凛】[r]
「た、たまには……ね」[lrcm]
　【和真】[r]
「どうしたんだ？　様子が変だけど」[lrcm]
　【凛】[r]
「え？　あー、ちょっと風邪引いてるかも」[lrcm]
確かに、いつもより少しばかり、声のトーンが落ちていた。[lrcm]
　【和真】[r]
「風邪？　風邪引いてるのに、こんなところに来て大丈夫なのか？」[lrcm]
　【凛】[r]
「いやー、別に大したことないから」[lrcm]
　【和真】[r]
「そ、そうか…………まあいいや。とりあえず、あがってあがって」[lrcm]
なんとなく、元気がないように感じる。[lrcm]
――――何かあったのだろうか。[lrcm]
そう思って、彼女をすぐさま部屋にあげた。[lrcm]

;;□：ブラックアウト／フェード2秒
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=1000 method=crossfade]
[fadeinmessage]
*chapter_2_22|第2章
;;□：自室(昼)
[image storage="部屋_回想.jpg" layer=base page=fore visible=true]

　【和真】[r]
「どうしたの？　なんかいつもより落ち着きがないけど」[lrcm]
　【凛】[r]
「え！？　いや、なんでもないよ？」[lrcm]
凛がうちに遊びに来ることも、大して珍しくはない。[lrcm]
男の部屋に入ってアタフタするというような感じでもない。[lrcm]
（何かあったんだ…………）[lrcm]
――――学校のこと？[lrcm]
――――家族のこと？[lrcm]
理由はわからないが、何かあってうちに来たというのは、間違いないだろう。[lrcm]
恋人である以上、オレが精一杯支えなくてはならない。[lrcm]
　【和真】[r]
「あ、そうだ。林檎、食べるだろ？」[lrcm]
　【凛】[r]
「あ、うん…………」[lrcm]
凛は林檎が大好物だ。[lrcm]
好きな物を口に入れれば、落ち着きを取り戻すだろう。[lrcm]
　【和真】[r]
「ちょっと待ってて、準備してくるから」[lrcm]

;;□：廊下(夕)／フェード1秒
[fadeoutmessage]
[transcombo storage="廊下回想.jpg" time=1000 method=crossfade]
[fadeinmessage]

台所の林檎を取りに向かう。[lrcm]

;;□：台所(夕)／フェード1秒
[fadeoutmessage]
[transcombo storage="台所回想.jpg" time=1000 method=crossfade]
[fadeinmessage]
*chapter_2_23|第2章
　【和真】[r]
「うーんと。あいつが喜びそうな、真っ赤な林檎はーっと」[lrcm]
戸棚の中にしまってある大きめのバスケットには、赤い林檎がいくつか置いてあった。[lrcm]
　【和真】[r]
「これが一番赤そうだな」[lrcm]
凛好みの、できるだけ全体が赤い林檎を選ぶ。[lrcm]
陽の光を受けて真っ赤に染まった林檎は、とても美味しそうだ。[lrcm]
　【和真】[r]
「それと、ナイフも必要だな」[lrcm]
オレは、ナイフの扱いが得意ではない。[lrcm]
というより、ほとんど台所に立ったことがないのだ。[lrcm]
ナイフの使い方を覚えなければいけないことは重々承知の上だが、特に料理を作る機会もないので、結局やらず仕舞いになっている。[lrcm]
[playbgm storage=rara.ogg loop=true]
　【和真】[r]
「いつか、凛に料理とか教わろうかな」[lrcm]
オレとは違い、凛は料理が得意だ。[lrcm]
家は名門、那須川家。[lrcm]
那須川と言ったら、この地方の重工業を取り仕切っている大金持ちだ。[lrcm]
英才教育を受けていて、将来を有望視された超エリート。[lrcm]
そんな凛が、なぜオレと付き合うことになったのか、オレにもまだよくわかっていない。[lrcm]
そもそも、凛と同じ学校に通えるのも、オレが受験勉強を死ぬ気で頑張ったおかげだ。[lrcm]
しかし、凛は特進クラスでオレは普通クラス。[lrcm]
頭の作りは全くもって違う。[lrcm]
そんな『人生勝ち組』の凛が告白してきたことに、[ruby text="いま"]未だ実感がわかない。[lrcm]
まあ、告白されるまでには、いろんなことがあったのは事実だけれど。[lrcm]
　【和真】[r]
「おっと、こんなことを考えてる暇はないな」[lrcm]
（さっさと持っていこう…………）[lrcm]
林檎、皿、ナイフ、ふきん。[lrcm]
必要なものは全て持ち、再び部屋へと向かう。[lrcm]
[stopbgm]
;;□：廊下(夕)／フェード1秒
[fadeoutmessage]
[transcombo storage="廊下回想.jpg" time=1000 method=crossfade]
[fadeinmessage]


;;□：自室(夕)／フェード1秒
[fadeoutmessage]
[transcombo storage="部屋_回想.jpg" time=1000 method=crossfade]
[fadeinmessage]

*chapter_2_24|第2章
　【和真】[r]
「お待たせ」[lrcm]
ふと凛のほうを見ると、彼女は向こうを向いて何かをしていた。[lrcm]
[playbgm storage=穢れ.ogg loop=true]
　【凛】[r]
「え？　あ！」[lrcm]
凛はオレに気がつくと、慌ててこちらを振り返る。[lrcm]
その拍子に――――[lrcm]
――――ゴロッ。[lrcm]
彼女の手のひらから、何かが落ちた。[lrcm]
（……………………え！？）[lrcm]
（オレの携帯電話…………！？）[lrcm]
　【凛】[r]
「あ、あの！　その…………！」[lrcm]
　【和真】[r]
「オレの携帯で、何をしてたんだ？」[lrcm]
紛れもなく、それはオレの物だ。[lrcm]
　【凛】[r]
「デザインいいなーと思って、ちょっと触ってみただけだよ……」[lrcm]
　【和真】[r]
「デザイン？　まあ、それならいいけど…………」[lrcm]
床に転げた、オレの携帯電話を拾う。[lrcm]
　【和真】[r]
「でも、落としたらダメだよ」[lrcm]
おかしくなっていないか確認するため、画面を見てみる。[lrcm]
　【和真】[r]
「ん…………！？」[lrcm]
――――メール作成画面が開かれていた。[lrcm]
宛先は、凛になっている。[lrcm]
（凛にメールなんて送ろうとしてたっけ…………？）[lrcm]
記憶が鮮明ではない。[lrcm]
　【凛】[r]
「落としちゃったのは謝るよ。ごめん」[lrcm]
　【和真】[r]
「いや、壊れてもないし、別に構わないよ」[lrcm]
オレは机の上に、持ってきたものを置いた。[lrcm]
　【和真】[r]
「とりあえず林檎を持ってきたから、食べたくなったら自分で剥いて食べていいからな」[lrcm]
　【凛】[r]
「あ、ありがとう…………」[lrcm]
その言葉を聞いて、オレはいつものように、凛の隣に座る。[lrcm]
　【凛】[r]
「あ………………」[lrcm]
;;[stopbgm]
　【和真】[r]
「今日は、どうしたんだ？」[lrcm]
何も用事がないのに、連絡なしでここにくるわけがない。[lrcm]
　【和真】[r]
「何か、あったのか…………？　話せる範囲でいいから、話してみて」[lrcm]
　【凛】[r]
「…………………………」[lrcm]

――――無言を貫く凛。[lrcm]
重い話なのだろうか。[lrcm]
（だとしたら、家族のこと…………？）[lrcm]
　【和真】[r]
「妹さんのことで、何かあったのか……？」[lrcm]
凛には、双子の妹がいる。[lrcm]
凛とは違い、彼女の妹は人見知りで無口ゆえ、両親から大変な叱責を食らっていると聞いたことがあった。[lrcm]
　【凛】[r]
「何もあるわけなんてない……！！！」[lrcm]
（……………………！？）[lrcm]
　【和真】[r]
「ご、ごめん。どうしたんだ……？」[lrcm]
彼女がここまで声を荒げるのを、オレは見たことがない。[lrcm]
今の彼女の心は、相当乱れているのだと悟った。[lrcm]
（しっかりとケアをしてあげないといけないな…………）[lrcm]
凛の恋人として、オレが彼女のサポートをするべきだ。[lrcm]
……………………。[lrcm]
妹の問題ではないとしたら、やはり両親とのことだろうか。[lrcm]
お金持ちの家だからこそ生まれる、家庭のトラブル。[lrcm]
実際、凛は両親に男女交際を禁止されていた。[lrcm]
だから本来、オレと凛は交際できないことになっている。[lrcm]
凛が周りに、オレと付き合っていることを隠しているのはそのためだ。[lrcm]
オレが凛の家に行くことはできない。[lrcm]
こうして、凛がオレの家を訪れるか、学校で逢い引きするしかないのだ。[lrcm]
今回も、そういう類いの話なのだろうか。[lrcm]
家庭の事情であれば、あまり他者が絡むべきではないのだろうが、事情が事情であれば仕方がない。[lrcm]
そんなことを考えていたオレは、次に凛が紡ぐ一言に、凍りつくことになった。[lrcm]

[stopbgm]

　【凛】[r]
「私と…………別れてほしい…………」[lrcm]
……………………。[lrcm]
…………。[lrcm]
;;[playbgm storage=奈落への旋律.ogg loop=true]
　【和真】[r]
「え……………………？」[lrcm]
オレの周りを流れていた時が、一瞬止まったかのように思えた。[lrcm]
耳に入ってきたその言葉は、オレの思考を止めるには充分すぎるものだった。[lrcm]

[playbgm storage=穢れ.ogg loop=true]

　【和真】[r]
「も、もう一度…………言ってもらえるか…………？」[lrcm]
　【凛】[r]
「私と別れてほしい。今すぐに…………！」[lrcm]
今度は先ほどよりも、更に強い口調で言い放つ凛。[lrcm]
（ど、どういう……………………）[lrcm]
　【和真】[r]
「な、なんで………………？」[lrcm]
　【凛】[r]
「理由なんてない。私が、あなたを嫌いになっただけ」[lrcm]
　【和真】[r]
「親にそう言えって言われたのか…………？」[lrcm]
信じられない気持ちで一杯だった。[lrcm]
昨日まで、好きだと言ってくれていた凛が、いきなり――――[lrcm]
　【凛】[r]
「違う。これは私の本心。あなたが嫌いになったの」[lrcm]
　【和真】[r]
「じょ、冗談はやめてほしい」[lrcm]
　【凛】[r]
「冗談なんかじゃないの。別れて、今すぐに」[lrcm]
彼女の口調は、徐々に強みを増していく。[lrcm]
オレは、何も考えられなくなっていた。[lrcm]
　【和真】[r]
「お、オレ……何かしたのか…………！？」[lrcm]
　【凛】[r]
「今までのことが積もりに積もったの。もう、あなたを見ていられない」[lrcm]
　【和真】[r]
「そ、そんな………………」[lrcm]
凛は立ち上がると、机に置きっ放しにしてあったノートをめくる。[lrcm]
　【凛】[r]
「私と比べて勉強もできないし、スポーツもできない。そんな男のどこに魅力があるっていうのよ」[lrcm]
　【和真】[r]
「オレだって、お前に追いつこうと必死で頑張ってる！」[lrcm]
付き合い始めてから、オレは努力を怠らないようになった。[lrcm]
毎日勉強するようになり、苦手だったスポーツも、常人ほどにはできるようになった。[lrcm]
　【凛】[r]
「必死になってる男って気持ち悪いのよね。消えてくれないかな」[lrcm]
　【和真】[r]
「…………………………」[lrcm]
我慢しきれずに、涙が浮かぶ。[lrcm]
;;[stopbgm]
*chapter_2_25|第2章
;;[playbgm storage=穢れ.ogg loop=true]
　【凛】[r]
「あーあ。泣いてる男が一番気持ち悪いんだよね」[lrcm]
数ヶ月しか経っていないけれど、努力してきた日々を否定され、オレは放心していた。[lrcm]
　【和真】[r]
「お前にオレの何がわかる…………」[lrcm]
　【凛】[r]
「は？　あなたのことなんて、知りたくもないんだけど？」[lrcm]
　【和真】[r]
「オレだって、今まで頑張ってきたんだ……お前に否定される筋合いはない…………」[lrcm]
　【凛】[r]
「だから、その頑張りが気持ち悪いって言ってんの。底辺野郎が何をやっても、所詮は底辺」[lrcm]
　【凛】[r]
「底辺はそれらしく、底辺同士で仲良くやってなさいよ」[lrcm]
　【和真】[r]
「オレは、底辺じゃない！」[lrcm]
　【凛】[r]
「いい、私はね？　那須川工業の令嬢なの。あなたとは違うの」[lrcm]
　【和真】[r]
「家なんて、関係ないだろ！」[lrcm]
　【凛】[r]
「ううん、関係あるの。というか、全ては家柄だから」[lrcm]
　【凛】[r]
「住む世界が違うって言ってんの！？　わかんないの！？」[lrcm]
　【和真】[r]
「そ、それは…………！」[lrcm]
　【凛】[r]
「悔しかったら、そこらへんの草を金に変えて見せなさいよ」[lrcm]
　【凛】[r]
「お金持ちはつらいわー。こんな底辺野郎の相手しなきゃいけないなんて」[lrcm]
　【和真】[r]
「底辺…………じゃない…………」[lrcm]
　【凛】[r]
「はぁ、何？　聞こえないんだけど。それとも何、底辺さんは日本語がまともに話せないの？」[lrcm]
　【和真】[r]
「底辺なんかじゃない…………」[lrcm]
　【凛】[r]
「いやいやいやいや、私を笑わせる気！？　ほんと気持ち悪いから、やめてほしいな」[lrcm]
　【凛】[r]
「底辺野郎さんは、いつまで生きてるつもりなの？　あなたは生きる価値なんてないよ」[lrcm]
　【凛】[r]
「酸素が無駄になるからさ、早く死んでよ」[lrcm]
　【和真】[r]
「だから…………………………！」[lrcm]
　【凛】[r]
「は！？　何？」[lrcm]
[stopbgm]
　【和真】[r]
「底辺なんかじゃないって言ってるだろぉおおおおお！！！」[lrcm]
次の瞬間、オレは突き飛ばしていた。[lrcm]
目の前の悪魔を――――[lrcm]
　【凛】[r]
「……………………！？」[lrcm]
凛は、後ろ向きに倒れていく。[lrcm]
――――異変は一瞬の出来事だった。[lrcm]

[playbgm storage=sekirei.ogg loop=true]

倒れる刹那、凛は近くにあった机の縁に手をかけようとした。[lrcm]
しかし、その手はうまく机の縁を掴むことができなかった。[lrcm]
代わりに、机上に置いてあった林檎や皿、ナイフを巻き込んで倒れていく。[lrcm]
そして――――[lrcm]
[playse storage=blood_flow.mp3]
――――ぐしゃぁあ！[lrcm]
（……………………！？）[lrcm]
目の前に見える、無数の赤線。[lrcm]
それは仰向けに倒れた凛の、首の後ろから両横に伸びていた。[lrcm]
彼女の周りに染みだした赤い液体は、瞬く間に水たまりを作った。[lrcm]
[stopbgm]
;;★：特殊効果(回想：終了)
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=1000 method=crossfade]
[fadeinmessage]

;;□：亜紗奈の部屋(夜)
[fadeoutmessage]
[transcombo storage="亜紗奈部屋_夜.jpg" time=1000 method=crossfade]
[fadeinmessage]

*chapter_2_26|第2章
　【和真】[r]
「うぅ………………！」[lrcm]
強烈な吐き気に襲われた。[lrcm]
たぶん、あの時の光景を思い出してしまったからだろう。[lrcm]
　【和真】[r]
「はぁ……はぁ…………」[lrcm]
呼吸は浅く、荒い。[lrcm]
夏の蒸し暑さも相まって、息苦しさを感じる。[lrcm]
（ベッドに横になりたい…………）[lrcm]

;;□：天井の電灯(夜：点灯無し)

そう思ってベッドに倒れ込むと、まぶたは重く、意識は徐々に薄れていった――――[lrcm]
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=2000 method=crossfade]
[fadeinmessage]
;;★：特殊効果(上下ワイピング：30％～90％，3秒)
……………………。[lrcm]
…………。[lrcm]
……。[lrcm]
*chapter_2_27|第2章
　【和真】[r]
「…………んん………………」[lrcm]
……………………。[lrcm]
気怠さを帯びて、意識は舞い戻ってくる。[lrcm]
（あ、オレ……寝てたのか…………）[lrcm]
まぶたを開けることさえ、ためらわれた。[lrcm]
思い出したくない記憶を無理矢理押し込め、睡眠の余韻に浸る。[lrcm]
[playbgm storage=rara.ogg loop=true]
あの鮮明な殺人の記憶は、夢なんてものでは説明できないような現実感のあるものだったために、全て夢だったというオチは期待できるわけがなかった。[lrcm]
――――だから、オレは逃避する。[lrcm]
この現実から逃げ続け、何の責任も取らずに死んでいく。[lrcm]
身勝手な行為だということを、頭では理解していた。[lrcm]
しかしこの体は、そんな利己的な行動を肯定するのだ。[lrcm]
凛の発言――――[lrcm]
カッとなってしまったことは事実だ。[lrcm]
しかし、冷静になるべきだった。[lrcm]
バカの独り言だと思っていれば、こんな結果になることはなかっただろう。[lrcm]
オレは愚かだった。[lrcm]
結局凛の言う通り、オレは生きる価値のない底辺の人間だったのだ。[lrcm]
言い返せなくて、ただ[ruby text="ふん"]憤[ruby text="まん"]懣のやる[ruby text="かた"]方を無くしていただけだったのかもしれない。[lrcm]
オレは自分に甘いだけの、愚か者だったのだ。[lrcm]
（甘いと言えば…………さっきから…………）[lrcm]
甘い芳香が、鼻孔を撫でるように刺激する。[lrcm]
それも今だけではなく、先ほどからずっと。[lrcm]
香水などつけているわけもなく、オレはこの香りの理由を説明できない。[lrcm]
加えて、先ほどから鼻先に感じる温かな風の流れ。[lrcm]
（なんだろう…………）[lrcm]
オレは、ゆっくりと目を開けてみた。[lrcm]
[fadeoutmessage]
[transcombo storage="亜紗奈部屋_夜.jpg" time=1000 method=crossfade]
[fadeinmessage]
;;▲：亜紗奈(欲情 部屋着 正面-アップ)
[image storage="部屋着_発情.png" layer=0 page=fore visible=true pos=right_center]

;;□：天井の電灯(夜：電灯無し，フェードイン／3秒)

（………………………………）[lrcm]
（………………）[lrcm]
[stopbgm]
　【和真】[r]
「…………………………！？」[lrcm]
予想だにしていない光景が、オレの思考と行動を停止させた。[lrcm]
その場に固まる。[lrcm]
;;[playbgm storage=rara.ogg loop=true]
　【亜紗奈】[r]
「あ、起きちゃった…………」[lrcm]
　【和真】[r]
「……………………え…………？」[lrcm]
仰向けに寝ているオレの目の前。[lrcm]
つまり、オレに覆い被さるようにして、亜紗奈はじっとこちらを見つめていた。[lrcm]
　【亜紗奈】[r]
「和真の寝顔がかわいいから…………」[lrcm]
　【和真】[r]
「………………へ……………………？」[lrcm]
;;[stopbgm]
;;[playbgm storage=奈落への旋律.ogg loop=true]
[image storage="部屋着_照れ.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「和真が悪いんだよ…………？」[lrcm]
そう言って、亜紗奈はオレの胸元に顔を埋（うず）めた。[lrcm]
亜紗奈の吐息が、こんなにも近くで聞こえる。[lrcm]
脈動は強みを増していく。[lrcm]
[image storage="部屋着_発情.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「いい匂い…………大好きな、和真の匂い…………」[lrcm]
　【和真】[r]
「あ、亜紗……奈…………？」[lrcm]
――――驚きを隠せない。[lrcm]
（……これ……は…………どういうことだ…………！？）[lrcm]
亜紗奈は、いったん顔を上げると――――[lrcm]
[image storage="部屋着_照れ.png" layer=0 page=fore visible=true pos=right_center]
　【亜紗奈】[r]
「あ、ダメだよ…………そんな顔しないで…………。私の好きな和真は、もっと優しい表情をしてる」[lrcm]
　【亜紗奈】[r]
「でも、今のその表情も、私はだーいすきだけど…………」[lrcm]
そう言って亜紗奈は、再び胸に顔を埋める。[lrcm]
彼女の吐息が、オレの胸を湿らせていく。[lrcm]
　【和真】[r]
「亜紗奈…………？　これは…………」[lrcm]
亜紗奈は、紅潮する顔を上げて－－－－[lrcm]
　【亜紗奈】[r]
「ごめんね……和真………………ずっとしっかり者の……幼なじみでいようと思ってたけど、やっぱり無理みたい…………」[lrcm]
　【和真】[r]
「どういう…………」[lrcm]
　【亜紗奈】[r]
「私、自分が思ってたよりももっともっと強く、和真のことが大好きだった…………」[lrcm]
潤しく甘美な目元は、オレの目を捉えて離さない。[lrcm]
　【亜紗奈】[r]
「ねぇ和真。私、もう我慢しなくていい…………？」[lrcm]
返事をする[ruby text="いとま"]暇もなく、亜紗奈の甘い唇が、オレの口元を覆う。[lrcm]
（あ、亜紗奈………………！）[lrcm]
今まで知らなかった快感が、脳内を駆け巡った。[lrcm]
夏の暑さとは毛色の違う、心地の良い温かさ。[lrcm]
柔らかな唇は、絶えずオレの唇を愛撫する。[lrcm]
舐めるように、貪るように。[lrcm]
亜紗奈はオレの唇を弄んでいる。[lrcm]
（………………………………！）[lrcm]
いつのまにかオレは、亜紗奈の体をしっかりと抱きしめていた。[lrcm]
いつからそうしていたのかは、よくわからない。[lrcm]
――――もうそんなこと、どうでもよかった。[lrcm]
今はただ目の前にあるこの快感に、気の赴くままに身を投じるだけだ。[lrcm]
それをオレの心が、体が、強く欲していた。[lrcm]
亜紗奈にされるがままに。[lrcm]
そして、オレのなすがままに。[lrcm]
まるで一つの塊になったように、本能の赴くまま、お互いを強く強く抱きしめあっていた。[lrcm]
;;[stopbgm]
[image storage="部屋着_照れ.png" layer=0 page=fore visible=false pos=right_center]
;;□：ブラックアウト／フェードアウト3秒
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=1000 method=crossfade]
[fadeinmessage]

;;♪：停止

;;♪：異変
;;★：あとで編集

;;□：天井の電灯(夜：消灯)
[fadeoutmessage]
[transcombo storage="闇天井.jpg" time=1000 method=crossfade]
[fadeinmessage]

*chapter_2_28|第2章
　【亜紗奈】[r]
「和真…………大好きだからね」[lrcm]

[playbgm storage=rara.ogg loop=true]

同じベッドで横になっている亜紗奈は、汗でしっとりとした前髪を整えながらそう言った。[lrcm]
　【亜紗奈】[r]
「これからも、私が和真を守る……大好きな和真を…………」[lrcm]
亜紗奈の潤った瞳は、こちらをじっと見つめる。[lrcm]
その熱い視線は、オレを魅了するには充分すぎるものだった。[lrcm]
　【和真】[r]
「あぁ…………」[lrcm]
この優しい空間がいつまでもあり続けることを、心の奥底から願う。[lrcm]
自分の罪を忘れ平穏を望むことは、決して許されることではない。[lrcm]
本当は独りで、この罪を背負っていかなくてはならないのだろう。[lrcm]
しかし、今のオレには亜紗奈がいる。[lrcm]
両親や友人は、オレの罪を聞けばすぐにでも警察を呼ぶだろう。[lrcm]
オレの平穏を奪う存在なんていらない、信じることができない。[lrcm]
――――でも、亜紗奈は違う。[lrcm]
オレのために、こうして尽くしてくれている。[lrcm]
独りで生きていくことなどできないというのは、最初からわかっていた。[lrcm]
だからこそオレは、理解者が欲しかったのだ。[lrcm]
昔から、オレが困ったときに支えてくれていた、幼なじみの亜紗奈。[lrcm]
その彼女が、今もこうしてオレを助けてくれている。[lrcm]
オレが亜紗奈を信じる判断材料は、それだけで充分だった。[lrcm]
……………………。[lrcm]
　【亜紗奈】[r]
「あ、そういえば――――」[lrcm]
亜紗奈の言葉に、オレははっと我に返った。[lrcm]
　【亜紗奈】[r]
「和真ってさ、お腹空いてない？」[lrcm]
（いきなりどうしたんだ…………？）[lrcm]
そう思ったのもつかの間、腹の虫の音はオレに空腹を知らせる。[lrcm]
――――ぐぅー。[lrcm]
　【和真】[r]
「あ………………」[lrcm]
思い出したかのように、空腹感が襲ってくる。[lrcm]
（そうか…………夕飯食べてなかったもんな…………）[lrcm]
――――というより、先ほどまで食欲がなかった。[lrcm]
あの凄惨な光景を目の当たりにしたのだから、当然のことだろう。[lrcm]
しかし今は亜紗奈という救いの存在によって、平常心を保っていることができる。[lrcm]
オレは、亜紗奈に恋愛感情を抱き始めていることに気がついた。[lrcm]
今さら過ぎるかもしれないが、ひどく混乱していたオレにとっては仕方のないことだ。[lrcm]
そんなことを気にする余裕など、ありはしなかったのだから。[lrcm]

[stopbgm]

　【亜紗奈】[r]
「私が何か作ってこようか？」[lrcm]
　【和真】[r]
「大丈夫なのか…………？」[lrcm]
　【亜紗奈】[r]
「おじいちゃん、いつも寝るの早いからもう寝てるだろうし、問題ないよ」[lrcm]
　【和真】[r]
「オレも手伝おうか？」[lrcm]
　【亜紗奈】[r]
「私一人で大丈夫だよ。美味しい手料理を食べさせてあげるからねっ」[lrcm]
そう言ってベッドから立ち上がる亜紗奈だったが――――[lrcm]
　【亜紗奈】[r]
「おっと…………！」[lrcm]
ふらついた亜紗奈が、ベッドに倒れ込む。[lrcm]
そして、オレのほうへと近づいてきて――――[lrcm]
　【亜紗奈】[r]
「ん………………」[lrcm]
（………………………………！？）[lrcm]
――――再び香る、甘い芳香。[lrcm]
唇には、温かくて柔らかいものが当たっていた。[lrcm]
亜紗奈の吐息が、オレの鼻先をくすぐる。[lrcm]
少しの静寂のあと、亜紗奈ははにかんで――――[lrcm]
　【亜紗奈】[r]
「もらっちゃった…………」[lrcm]
そう言って亜紗奈は嬉しそうに、部屋を出て行った。[lrcm]
………………………………。[lrcm]
………………。[lrcm]
夜食はエビピラフだった。[lrcm]

;;□：ブラックアウト／フェードアウト2秒
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=2000 method=crossfade]
[fadeinmessage]
*chapter_2_29|第2章
…………………………。[lrcm]
…………。[lrcm]
……。[lrcm]
[playse storage=door_a_open.mp3]
――――ガチャ。[lrcm]
（ん……………………）[lrcm]

;;□：天井の電灯(夜：消灯)
[fadeoutmessage]
[transcombo storage="闇天井.jpg" time=1000 method=crossfade]
[fadeinmessage]
*chapter_2_30|第2章
ふいに物音がして目が覚めた。[lrcm]
（扉の…………音…………？）[lrcm]
亜紗奈が戻ってきたのだろうか。[lrcm]

;;□：ブラックアウト／フェード2秒
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=2000 method=crossfade]
[fadeinmessage]

*chapter_2_31|第2章
気を遣わせてはいけないと思い、もう一度目を瞑る。[lrcm]
[playse storage=door_a_close.mp3]
――――ガチャン。[lrcm]
扉の閉まる音とともに、タンタンという足音が微かに聞こえてきた。[lrcm]
（……………………………………）[lrcm]
足音は徐々に近づき、オレの真横を通り過ぎる。[lrcm]
（…………………………）[lrcm]
（……………）[lrcm]
（ん………………？）[lrcm]

;;[stopbgm]

;;[playbgm storage=穢れ.ogg loop=true]
ある[ruby text="いっ"]一[ruby text="とき"]時から何の物音もしなくなったことに、えも言われぬ疑問を感じた。[lrcm]
（どうしたんだろう…………）[lrcm]
そう思って、薄目を開けると――――[lrcm]

[playbgm storage=sekirei.ogg loop=true]

;;□：亜紗奈の部屋窓アップ(夜：消灯)
[image storage="部屋着_病み目_闇.png" layer=0 page=fore visible=true pos=right_center]
（………………………………！？）[lrcm]
不穏な雰囲気をまとった姿が、そこにはあった。[lrcm]
恐ろしげな光景を目の当たりにし、全身が凍りつく感覚を覚える。[lrcm]
（亜紗…………奈………………！？）[lrcm]
微かな月の光に照らされて、焦点の定まっていない目が強調されている。[lrcm]
その口元は、その目とは不釣り合いなほどに――――[lrcm]
（笑ってる……………………！？）[lrcm]
全身が総毛立つ感覚。[lrcm]
心臓の鼓動が、痛みをともなうほど激しく脈を打つ。[lrcm]
呼吸さえ忘れていしまいそうになるほどの異様な光景。[lrcm]
暗闇だからという理由だけでは済まされないほど、その姿は恐怖に満ちていた。[lrcm]
　【亜紗奈】[r]
「……………………った…………」[lrcm]
（………………………………！？）[lrcm]
――――彼女の口は、何かを呟いている。[lrcm]
　【亜紗奈】[r]
「…………か…………た…………」[lrcm]
（亜紗奈は何を言って……？）[lrcm]
――――そのとき、オレには聞こえてしまった。[lrcm]
亜紗奈は確かに、こんな言葉を紡いだのだ。[lrcm]
[stopbgm]
…………………………………。[lrcm]
………………。[lrcm]
　【亜紗奈】[r]
「…………勝った…………………………」[lrcm]
（……………………………！？）[lrcm]
（勝った………………！？）[lrcm]
オレには、その言葉の指し示す意味が理解できない。[lrcm]
　【亜紗奈】[r]
「…………あいつに…………勝った………………！」[lrcm]
（あ、あいつ……………………！？）[lrcm]
段々と表情が崩れていく亜紗奈を、息を潜めながら見ていることしかできなかった。[lrcm]
目の前の少女は、オレの知っている少女ではない。[lrcm]
オレの幼なじみは、こんな恐ろしい表情なんてしない。[lrcm]
　【亜紗奈】[r]
「…………これで…………愛しい和真は、私のもの…………」[lrcm]
　【亜紗奈】[r]
「…………そして、私は永遠に…………和真のもの…………」[lrcm]
彼女が浮かべた恍惚の表情は、闇夜に[ruby text="は"]映えると途端に、恐ろしさを増した。[lrcm]
怖くなって、右手でシーツを掴む。[lrcm]
えも言われぬ恐怖から呼吸は荒く、不規則な脈動を繰り返していた。[lrcm]
　【亜紗奈】[r]
「和真…………愛してるから……ね………………？」[lrcm]
（………………………………）[lrcm]
[image storage="部屋着_病み目_闇.png" layer=0 page=fore visible=false pos=right_center]
亜紗奈はそう言って、ベッドへと入り込む。[lrcm]
（温かい……………………）[lrcm]
夏の暑さとは異なる、肌のぬくもり。[lrcm]
すぐ隣にいるだけで、その心地よい熱は伝わってくる。[lrcm]
………………………………。[lrcm]

[playbgm storage=rara.ogg loop=true]

（そうだ…………亜紗奈はオレのことを愛してくれているんだ………………！）[lrcm]
*chapter_2_32|第2章
さっきの表情は、オレが見た空想だ。[lrcm]
オレは、自分を信じてくれる人を疑おうとしているのか。[lrcm]
そんなこと、オレ自身が許さない。[lrcm]
何故オレは、亜紗奈を疑うなんてしてしまったのだろう。[lrcm]
亜紗奈は確かに、オレに好意を持ってくれている。[lrcm]
――――それに応えたい。[lrcm]
応えなければならない。[lrcm]
亜紗奈に救いを求める代償がそれなら、オレは全力で遂行する。[lrcm]
そうすることで、オレは助かるのだ。[lrcm]
オレが彼女の気持ちに応えることによって、彼女自身も救われる。[lrcm]
それがこの契約の真実の目的であり真相であるということは、言われなくともよく理解していた。[lrcm]
――――オレが彼女を救う。[lrcm]
そして、彼女はオレのことを救ってくれる。[lrcm]
小さい頃からずっと同じだ。[lrcm]
ただ、それが昔よりもずっと深いものに変わっただけ――――[lrcm]
オレは、昨日以前のオレと同じように生きていく。[lrcm]
自分の罪を受け入れず、逃避の道を選ぶ。[lrcm]
それは非人道的なのかもしれないが、生物としては至極当然のことだ。[lrcm]
人間は人間である前に生物なのだから、その道を選んで何が悪い。[lrcm]
オレは明日からも、何食わぬ顔で生活をする。[lrcm]
亜紗奈も、それを望んでいるだろう。[lrcm]
ただ一つだけ変わるのは、オレが凛ではなく亜紗奈を選ぶということ。[lrcm]
最初から、凛と交際などしていなかったことにすればいい。[lrcm]
凛は厳格な両親にオレと付き合っていることを隠すため、オレと付き合っていることは誰にも言っていない。[lrcm]
デートなんてものも、わざわざ隣町に行くかオレの部屋で遊ぶかの二択だった。[lrcm]
――――誰も気がついてはいないはずだ。[lrcm]
学校でも極力顔を合わせなかったし、友人に悟られるようなこともなかった。[lrcm]
このまま隠し通せるはずだ。[lrcm]
だって――――[lrcm]
――――オレには亜紗奈がついてくれている。[lrcm]
オレを全力で守ると誓った亜紗奈が、隣で寄り添ってくれている。[lrcm]
今もこうやって、オレの体を抱きしめている。[lrcm]
それだけで、オレの心は満たされた。[lrcm]
寄り添ってくれる存在を、オレはずっと愛したいと思ったのだ。[lrcm]
オレの心の奥底には理解不能で気味の悪い、どろどろとしたコールタールのようなものが流れている。[lrcm]
そんなものが絶えずオレの魂を苛み、ぎりぎりと潰そうとしてくるのだ。[lrcm]
その度に亜紗奈という存在が、癒やし、安らぎを与えてくれる。[lrcm]
それだけで、オレが亜紗奈と一緒にいる理由を説明するには充分だった。[lrcm]
今もこうして隣で横たわる亜紗奈が、瞳孔を見開き不気味に微笑んでいても―――――[lrcm]
――――オレの心はなんの疑いもなく、彼女とともにあるのだった。[lrcm]
[stopbgm]
;;□：ブラックアウト／フェード2秒
[fadeoutmessage]
[transcombo storage="ブラックアウト.jpg" time=2000 method=crossfade]
[fadeinmessage]
;;♪：停止
*chapter_2_33|第2章
;;シナリオ3へ
[jump storage="chapter_3.ks"]
